### ISSUE TITLE
aria2无法下载

### ISSUE THREAD

**Issue by Gordon-shin** [ywwzwb/XunleiToAria2#1]
显示error code =22
status=400

**Comment by ywwzwb** [comment]
你这个错误是从哪里出来的?
这个插件只支持 token 验证方式, 你的aria2 版本是多少呢?

**Comment by Gordon-shin** [comment]
貌似是文件的原因 又试了下别的文件aria2直接 not complete

#用户名
#rpc-user=user
#密码
#rpc-passwd=passwd
#设置加密的密钥
#rpc-secret=secret
#允许rpc
enable-rpc=true
#允许所有来源, web界面跨域权限需要
rpc-allow-origin-all=true
#是否启用https加密，启用之后要设置公钥,私钥的文件路径
#rpc-secure=true
#启用加密设置公钥
#rpc-certificate=/home/acgotaku/.config/aria2/example.crt
#启用加密设置私钥
#rpc-private-key=/home/acgotaku/.config/aria2/example.key
#允许外部访问，false的话只监听本地端口
rpc-listen-all=true
#RPC端口, 仅当默认端口被占用时修改
#rpc-listen-port=6800
#最大同时下载数(任务数), 路由建议值: 3
max-concurrent-downloads=3
#断点续传
continue=true
#同服务器连接数
max-connection-per-server=10
#最小文件分片大小, 下载线程数上限取决于能分出多少片, 对于小文件重要
min-split-size=1M
#单文件最大线程数, 路由建议值: 5
split=16
#下载速度限制
max-overall-download-limit=0
#单文件速度限制
max-download-limit=0
#上传速度限制
max-overall-upload-limit=0
#单文件速度限制
max-upload-limit=0
#断开速度过慢的连接
#lowest-speed-limit=0
#验证用，需要1.16.1之后的release版本
#referer=*
#文件保存路径, 默认为当前启动位置
#dir=F:\idm
#文件缓存, 使用内置的文件缓存, 如果你不相信Linux内核文件缓存和磁盘内置缓存时使用, 需要1.16及以上版本
#disk-cache=0
#另一种Linux文件缓存方式, 使用前确保您使用的内核支持此选项, 需要1.15及以上版本(?)
#enable-mmap=true
#文件预分配, 能有效降低文件碎片, 提高磁盘性能. 缺点是预分配时间较长
#所需时间 none < falloc ? trunc << prealloc, falloc和trunc需要文件系统和内核支持
file-allocation=prealloc
#不进行证书校验
check-certificate=false
rpc-secret=secret
user-agent=netdisk;5.4.10.3;PC;PC-Windows;6.2.9200;WindowsBaiduYunGuanJia
input-file=D:\程序\aria2-1.26.0-win-64bit-build1\aria2-1.26.0-win-64bit-build1\aria2.session
save-session=D:\程序\aria2-1.26.0-win-64bit-build1\aria2-1.26.0-win-64bit-build1\aria2.session
save-session-interval=10
force-save=true
bt-hash-check-seed=true
bt-seed-unverified=true
bt-save-metadata=true
max-tries=0
continue=true
og=D:\程序\aria2-1.26.0-win-64bit-build1\aria2-1.26.0-win-64bit-build1\aria.log

这是我aria2 的配置。。

服务器地址是http://token:secret@localhost:6800/jsonrpc

版本是1.27.1 拓展能连接到aria2的

**Comment by ywwzwb** [comment]
抱歉, 最近有点忙, 我提交新版本了, 你再试试呢

**Comment by Gordon-shin** [comment]
有些资源403 没有权限是怎么回事？

**Comment by ywwzwb** [comment]
具体是什么资源, 能否提供一下, 是每次下载那个资源都会出问题吗?

**Comment by ywwzwb** [comment]
应该是迅雷服务器的问题, 我这边也出现这个问题, 错误的任务, 重试一下就好了, 应该是迅雷服务器的问题
