### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by zelda0079** [ywwzwb/XunleiToAria2#10]
当我按了下载到ARIA2, 然后查看时
出现这样
很多资源都会这样
这是什么情况?
![issue](https://cloud.githubusercontent.com/assets/19840375/22603236/86a6a45c-ea81-11e6-9d40-c3a4ae553c15.png)

**Comment by ywwzwb** [comment]
你是使用的直接下载到aira2 还是通过迅雷下载到aria2? 另外, 是所有资源都会下载失败还是部分资源失败

**Comment by zelda0079** [comment]
之前是我错, 我没有租会员, 后来我租了, 还是不能用, 倒是另一款能用
https://chrome.google.com/webstore/detail/thunderlixianassistant/eehlmkfpnagoieibahhcghphdbjcdmen?hl=zh-TW

我是用直接下载到ARIA2的方法(在离线页面那个按钮)

**Comment by zelda0079** [comment]
ARIA2版本是1.31.0

**Comment by zelda0079** [comment]
![default](https://cloud.githubusercontent.com/assets/19840375/23098582/acc5257a-f68c-11e6-8348-11eb8e41aa6e.png)

同一个资源, 出错的是这款插件, 有速度的是另一款插件(上面连结), 所以我想应该不是资源问题

**Comment by ywwzwb** [comment]
可否提供另外那个插件的名字和下载地址

**Comment by ywwzwb** [comment]
感谢你的支持, 错误原因在于 cookie信息错误, 已经更新到 google 商店

**Comment by zelda0079** [comment]
不客气, 不过最近租了会员资源都已经解决了, 短时间没办法帮你测试了
