### ISSUE TITLE
Token服务器怎么填？

### ISSUE THREAD

**Issue by zhouhounan** [ywwzwb/XunleiToAria2#12]
![1](https://cloud.githubusercontent.com/assets/17348292/25118854/81f8dce2-244a-11e7-88e3-c968d82b79ee.jpg)
如图 谁能告诉 我吗？zhouhounan@gmail.com

**Comment by ywwzwb** [comment]
这是你的 aria2 服务器地址. 验证方式必须使用 token 方式验证.

**Comment by zhouhounan** [comment]
我用的本机。要怎么填写呢。就是不明白什么叫TOken。我只是小白用户。另外这个有Q群吗。这样有问题也好请教呀

**Comment by ywwzwb** [comment]
你是什么系统? aria2 有一个配置文件, 里面有一项是
rpc-secret=xxxx 
xxxx就是你的 token

**Comment by zhouhounan** [comment]
我用的是Windows10   配置文化里的语句默认是这样的：
 <tr>
        <td id="L6" class="blob-num js-line-number" data-line-number="6"></td>
        <td id="LC6" class="blob-code blob-code-inner js-file-line">#rpc-secret=secret</td>
      </tr>
只有这一句，那Token就是secret?

**Comment by ywwzwb** [comment]
要把前面的那个#去掉才能生效, 如果你不改后面的东西, token 就是secret

**Comment by zhouhounan** [comment]
![qq 20170419120744](https://cloud.githubusercontent.com/assets/17348292/25162914/cf3daa92-24f8-11e7-951c-7b2a556c5ef9.png)
解决了。谢谢。我还找了一个带图形化界面的版本，用起来很方便。哈哈
