### ISSUE TITLE
[建议]免掉添加服务器时的验证

### ISSUE THREAD

**Issue by shap2zj** [ywwzwb/XunleiToAria2#16]
我的服务器在添加的时候显示 “连接错误”。其实服务器是在线的，服务器地址也都对。所以希望可以在提示连接错误的时候添加一个按钮，让用户选择是否愿意仍然添加。

**Comment by ywwzwb** [comment]
好建议, 后面会加上

**Comment by ywwzwb** [comment]
功能加上了, 感谢支持
