### ISSUE TITLE
迅雷离线页面经过和客服详谈已经不再启用

### ISSUE THREAD

**Issue by macheteHot** [ywwzwb/XunleiToAria2#18]
迅雷离线页面经过和客服详谈已经不再启用，新页面是这个，http://lixian.xunlei.com/xl9/space.html

**Comment by greedygod** [comment]
同上，应该是最近两天才开始的，跟客服了解到新的离线页面是http://lixian.xunlei.com/xl9/space.html
从17号开始在旧版离线页面添加的任务进度始终会是0%，需要在新页面添加离线任务才能正常工作
——望更新，谢谢！

**Comment by geekotaku** [comment]
听说旧版页面马上要关了，希望尽快更新

**Comment by greedygod** [comment]
可能不好搞了。我跟另一个插件作者聊之后，发现新版压根没做离线下载，后续取回的时候，是用原始地址进行下载的，并且调用客户端迅雷来p2p加速。所以怀疑迅雷出不起离线服务器的资源了

**Comment by macheteHot** [comment]
yep 我也联系客服了，确实是这样的情况，需要使用迅雷9才能用

在 2017年6月27日 下午8:32，greedygod <notifications@github.com>写道：

**Comment by ywwzwb** [comment]
我也试过页面上的取回本地功能, 发现只是直接给出原始地址, 后续我再看一下

**Comment by duhd1993** [comment]
我是最近一周左右才遇到旧版失效的，之前正常...这下不知道用什么工具下载了。百度远不如迅雷耐操。

**Comment by marcosteam** [comment]
是的，旧版的导出已经全部死链
