### ISSUE TITLE
一个下载的BUG，描述比较难，看图吧

### ISSUE THREAD

**Issue by s123077** [ywwzwb/XunleiToAria2#4]
![qq 20161030150227](https://cloud.githubusercontent.com/assets/22574931/19834993/c42321cc-9eb2-11e6-9c3d-4249140dde30.png)
就是已经下载到http://dynamic.cloud.vip.xunlei.com/的任务，在点 界面里的“下载到ARIA2,提示”加载中“，无法下载。而右键菜单连接下载到ARIA2正常

**Comment by jc3213** [comment]
这个应该是交互上的一个BUG，你通过设置，测试连接，成功显示版本号以后，再点这个下载就正常了。

这里可能需要修改这部分的代码才能修复这个问题，比如打开迅雷界面后就进行一次交互，或者点右键菜单添加了 迅雷离线Aria2 菜单的同时进行一次交互？ 这个估计得听听作者得意见了。Aria2得图形界面大概每3秒就进行一次RPC通信以刷新下载进度等信息。

我不太熟悉Chrome得API帮不上忙

@ywwzwb

**Comment by ywwzwb** [comment]
感谢你的反馈, 最近比较忙, 我会尽快修复, 同时新版本也已经发布了, 欢迎试用反馈
