### ISSUE TITLE
小白问题，显示连接错误

### ISSUE THREAD

**Issue by AbstractJungle** [ywwzwb/XunleiToAria2#5]
![fasdasd](https://cloud.githubusercontent.com/assets/23163373/19847022/b74cc242-9f7e-11e6-9b0c-4eb8552ee140.JPG)
![dasdas](https://cloud.githubusercontent.com/assets/23163373/19847023/b8c84be6-9f7e-11e6-8296-743417a31255.JPG)

设置时显示连接错误，但是yaaw可以正常连接到路由器上的aria2

**Comment by ywwzwb** [comment]
只支持 token 方式验证, 这种无需密码验证的方式不支持的, 建议改成 token 验证模式, 具体修改方法可以搜索

**Comment by AbstractJungle** [comment]
好的，感谢
