### ISSUE TITLE
下载有图片的文件时会下载图片而不是文件

### ISSUE THREAD

**Issue by jc3213** [ywwzwb/XunleiToAria2#6]
个人是在nyaa上遇到的。点击Download下载种子，不管是下载到迅雷离线还是直接通过Aria2下载都会下载图片而不是种子文件。

希望遇到这类情况时将菜单分为 下载图片 跟 下载链接 两个部分（参考其他下载软件）

![nyaa](https://cloud.githubusercontent.com/assets/8744936/19881002/10dea1fe-a03d-11e6-8338-7ebdd6789439.png)
![aria2](https://cloud.githubusercontent.com/assets/8744936/19880999/0b04bea8-a03d-11e6-9058-1b781744482d.png)

**Comment by ywwzwb** [comment]
老司机啊

**Comment by jc3213** [comment]
我只是上去下番剧而已。现在各大网站乱买版权，无法在同一个网站上看所有番，而且还有些番网上看不到了，累觉无爱，只能自己下了。

另外扩展本身跟Aria2的交互逻辑也必须改一下。否则第一次下载时必定会出现`正在加载`对话框然后卡住，然后要刷新一次才能正常下载。或者先打开设置，测试一下连接，再下载才能正常。

**Comment by ywwzwb** [comment]
新版本已发布, 现在右键点击图片, 可以直接下载图片, 或者下载图片对应的链接, 另外, 第一次下载必定卡住的 bug 也有修复, 欢迎试用反馈
