### ISSUE TITLE
用这个迅雷离线的前提一定要是迅雷会员吗？

### ISSUE THREAD

**Issue by rong2er** [ywwzwb/XunleiToAria2#9]
我不是迅雷会员 任务可以添加，但是没几秒就提示 红字 出错

**Comment by rong2er** [comment]
红字是：HTTP response header was bad or unexpected

还有：aria2 saw the specified number of "resource not found" error. See --max-file-not-found option

**Comment by ywwzwb** [comment]
需要迅雷会员才可以的, 如果不是会员的话, 下载不下来的, 我一般是买的1分钱会员
另外, 迅雷的服务器经常会出错, 如果下载失败, 重试几次吧.
